import { StyleSheet } from 'react-native';
import { radius, spacing, ThemeColors } from '../theme';

export function createStyles(colors: ThemeColors) {
  return StyleSheet.create({
    container: {
      flex: 1,
    },
    loadingContainer: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: spacing.sm,
    },
    loadingText: { color: colors.textMuted, fontSize: 14 },
    dot: {
      flexDirection: 'column',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 1,
      // A fixed size (not sized to the route text) so the heading arrowhead around it —
      // HeadingArrowBadge, which needs this exact size — is placed identically for every vehicle.
      width: 40,
      height: 38,
      borderRadius: radius.sm,
      paddingHorizontal: 2,
      paddingVertical: 3,
      borderWidth: 2,
      borderColor: '#FFFFFF',
    },
    dotText: { color: '#FFFFFF', fontSize: 10, fontWeight: '700' },
    // A stop's own marker: a small hollow-looking badge (white fill, coloured ring) so it
    // reads as quieter than a vehicle's solid, bigger badge even before either one moves.
    stopBadge: {
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: '#FFFFFF',
      borderWidth: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    locateButton: {
      position: 'absolute',
      right: spacing.md,
      bottom: spacing.md,
    },
    infoCard: {
      position: 'absolute',
      bottom: spacing.sm,
      left: spacing.sm,
      right: spacing.sm,
      backgroundColor: colors.surface,
      borderRadius: radius.md,
      padding: spacing.md,
      borderWidth: 2,
      borderColor: colors.primary,
      elevation: 8,
      shadowColor: '#000',
      shadowOpacity: 0.3,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
    },
    infoRoute: { fontWeight: '700', color: colors.text },
    infoHeadsign: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
    infoNextStopLabel: { color: colors.text, fontSize: 13, fontWeight: '600', marginTop: spacing.xs },
    infoOnTime: { color: colors.success, fontSize: 12, marginTop: 2 },
    infoDelayed: { color: colors.danger, fontSize: 12, marginTop: 2 },
    infoCancelled: { color: colors.danger, fontSize: 12, marginTop: 2, fontWeight: '700' },
    infoClear: { color: colors.accent, fontWeight: '600', fontSize: 12, marginTop: spacing.xs },
    infoUpdatesIn: { color: colors.textMuted, fontSize: 11, marginTop: 2 },
    collisionBackdrop: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: 'rgba(0, 0, 0, 0.35)',
      alignItems: 'center',
      justifyContent: 'center',
      padding: spacing.lg,
    },
    collisionCard: {
      width: '100%',
      maxWidth: 320,
      backgroundColor: colors.surface,
      borderRadius: radius.lg,
      padding: spacing.md,
      gap: spacing.xs,
      elevation: 8,
      shadowColor: '#000',
      shadowOpacity: 0.3,
      shadowRadius: 8,
      shadowOffset: { width: 0, height: 4 },
    },
    collisionTitle: {
      fontWeight: '700',
      color: colors.text,
      fontSize: 15,
      marginBottom: spacing.xs,
    },
    collisionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.sm,
      borderRadius: radius.md,
      backgroundColor: colors.background,
    },
    collisionRowText: { color: colors.text, fontSize: 14, fontWeight: '600', flex: 1 },
  });
}
